// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("lumberjack")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/lumberjackexporter"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
